subtitutions:
  name: "detagrid-switch"
  friendly_name: "DetaGrid Switch"

packages:
  remote_package:
    url: https://github.com/s-gordon/ESPHome-Configs
    ref: main
    refresh: 1d
    files:
      # uncomment relevant lines to your device

      # -- detagrid smart switch
      # - esphome/packages/config/base.yaml
      # - esphome/packages/config/detagrid-smart-switch/1-gang.yaml
      # - esphome/packages/config/detagrid-smart-switch/2-gang.yaml
      # - esphome/packages/config/detagrid-smart-switch/3-gang.yaml

      # BK72XX boards
      # - esphome/packages/config/base-BK72XX.yaml
      # - esphome/packages/config/detagrid-smart-switch/DETA-Grid-Connect-Smart-Switch-2-gang_BK72XX

# Enable Home Assistant API
api:
  encryption:
    key: "<secret>"

ota:
  password: !secret ota_password

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  # fast_connect: on
  # Fallback hotspot (captive portal) in case wifi connection fails
  # ap:
  #   ssid: "${name}"
      